### ISSUE TITLE
Kompilere 

### ISSUE THREAD

**Issue by olaven** [AlphonseSantoro/CyberMafia#1]
Forsøker å kompilere, men den finner ikke pakkene som er importert. Hvordan kan jeg fikse det? 😅

**Comment by AlphonseSantoro** [comment]
Skal se på det :) har brukt jasypt til å kryptere så e må nok bare få adda dependency jar til git også

**Comment by AlphonseSantoro** [comment]
I morra skal e fjerne dependencies for dinne repositorien, da e har flytta all datebase håndteringa til serveren. Da gjenstår det bare å få skaffa en plass til å hoste serveren. Serveren e nesten ferdig, den mangla bare en måte å gjenkjenne input og prosessere det på riktig måte, når det e ferdig skal det ikke være nødvendig for andre å måtte kompilere serveren også da planen e at den skal kjøre 24/7.

**Comment by AlphonseSantoro** [comment]
I readme ligge det links til dependencies m.m. tror der ligge alt du trenge for å kompilere :)

**Comment by olaven** [comment]
Nice! Jeg skal kikke på det i kveld :)
